# INF360 VA - Programming with Python
# Jarrett Smolarkiewicz
# Assignment 2

# 1 point - Initial comments*
# 1 point - Use at least 2 different comparison operators.
# 1 point - Use at least 1 boolean operator (and, or, not).
# 2 points - Write at least 1 if statement that MUST contain 2 elif statements and 1 else statement.
# 2 points - Write at least 1 while statement that contains a break and continue.
# 2 points - Write at least 1 for loop using the range() method.
# 1 point - Use the import keyword to import the random module. Use the random.randint() function somewhere in your script.

import random

randomNum = random.randint(1, 10)

for i in range(0, randomNum):
        print("-" * i + ">")
        
print("Welcome to this Python Program!")
print("How many years old are you?")

while True:
    userAge = input("> ")
    if len(userAge) > 0:
        break
    else:
        print("That was not a valid age! Please try again...")
        continue

if int(userAge) == 18:
    print("So you're 18... Must feel good to be an adult!")
elif int(userAge) == randomNum:
    print("WooHoo!")
    print("Your age is identical to the random number generated by this program!")
    print("The random number was " + str(randomNum) + ".")
    print("What are the odds, right???!!!")
elif int(userAge) >= 16 and int(userAge) <= 122:
    print("Hope you're eager to learn by using this Python program today!")
elif int(userAge) > 0 and int(userAge) < 16:
    print("So you aren't even driving on your own yet, and you're using a Python program?")
    print("Impressive!")
else: 
    print("C'mon! Who is that old?! Stop messing around!")

